### PR TITLE
[GROUND-4] Less expensive internal key generation

### PR DESCRIPTION
**Pull request by vsreekanti**
* Make all unique IDs `long`s (or `bigint`s). 
* Allow for (eventual) distributed ID generation by giving each machine a unique prefix.
* Use a `synchronized` ID generator on each machine. 
* For Neo4j, make all IDs globally unique (instead of unique amongst items, versions, etc.).

### CODE REVIEW

**Comment by vsreekanti** [comment]
Note that the Travis build is failing because of the hive plugin build failure. This won't be an issue once @ramach and @akon-dey finish refactoring the Hive plugin to use the REST APIs instead of hooking into the internal APIs.

**Comment by ramach** [comment]
Yes we're working on this. Will have first patch the coming week. Still
curious - build was working before. What changed?

Krishna

**Comment by vsreekanti** [comment]
I changed the internal interfaces. That's what this PR is.

**Comment by ramach** [comment]
Yes. I see that. Removing those low level dependencies. Will update

Regards
Krishna

**Comment by tarpdalton** [comment]
The new ids look good. I think it will be helpful when creating ways to link nodes that are ingested into ground from separate sources

**Pull request merged**
