### PR TITLE
added swagger static docs

### PR DESCRIPTION
**Pull request by tarpdalton**
#16

If we change the settings on github to point the github site to the docs folder on master branch, then the documentation would be available at https://ground-context.github.io/ground/api

These files are the standalone [swagger-ui](https://github.com/swagger-api/swagger-ui/tree/master/dist) files. I added the swagger spec json file that was generated from the code to index.html. It will need to be replaced any time the api is edited.

### CODE REVIEW

**Comment by vsreekanti** [comment]
I'm we have to regenerate these files every time we update the docs?

**Comment by tarpdalton** [comment]
he have to generate the json file and re add it to the html. Let me see if I can make a simpler way for the docs to update

**Comment by tarpdalton** [comment]
Now to update the documentation you would just replace the `/docs/api/swagger.json` file with http://localhost:8080/swagger.json (when the ground server is running). We could probably write a script to automate it though.

**Comment by tarpdalton** [comment]
here is an example https://tarpdalton.github.io/swag-test/swagger

**Comment by vsreekanti** [comment]
Great, looks good. If we put this on a `gh-pages` branch, then Github Pages should take care of the rest of the routing for us, right?

**Comment by tarpdalton** [comment]
you can put it on the gh-pages branch, or in the docs folder of the master branch. you just have to set which one in the settings page for the repo

**Pull request merged**
